### ISSUE TITLE
Beta is full

### ISSUE THREAD

**Issue by HusseinElhaddad** [paulplant/xdrip4ios_docs#15]
Cannot install as the number of testers have reached its limit. Is there any other way?

**Comment by paulplant** [comment]
This request is not an issue with the app documentation so I need to close this.

Please see the online documentation for all support options related to the xDrip4iOS app:

https://xdrip4ios.readthedocs.io

Specifically, you can join the Facebook group linked here:

https://xdrip4ios.readthedocs.io/en/latest/#where-can-i-get-help

Thanks for your interest!
