### ISSUE TITLE
Dexcom One+ not supported

### ISSUE THREAD

**Issue by lvi-jonathan** [paulplant/xdrip4ios_docs#20]
Hi there,

I just received a Dexcom One+ yesterday and it's of course too new to be supported by Xdrip. Is there any chance i can help getting it to work? 

Let me know what i can do. 

Thanks!

John

**Comment by paulplant** [comment]
This is the repository for the online documentation, not for the xDrip4iOS app.

As ONE+ compatibility is now included in the main app, I'll close this.
